
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerConnectorService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://qa1.customerconnector.bwin.intranet/1.2/CustomerConnector.svc?wsdl")
public class CustomerConnectorService
    extends Service
{

    private final static URL CUSTOMERCONNECTORSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERCONNECTORSERVICE_EXCEPTION;
    private final static QName CUSTOMERCONNECTORSERVICE_QNAME = new QName("http://tempuri.org/", "CustomerConnectorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://qa1.customerconnector.bwin.intranet/1.2/CustomerConnector.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERCONNECTORSERVICE_WSDL_LOCATION = url;
        CUSTOMERCONNECTORSERVICE_EXCEPTION = e;
    }

    public CustomerConnectorService() {
        super(__getWsdlLocation(), CUSTOMERCONNECTORSERVICE_QNAME);
    }

    public CustomerConnectorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERCONNECTORSERVICE_QNAME, features);
    }

    public CustomerConnectorService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERCONNECTORSERVICE_QNAME);
    }

    public CustomerConnectorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERCONNECTORSERVICE_QNAME, features);
    }

    public CustomerConnectorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerConnectorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICustomerConnectorService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICustomerConnectorService")
    public ICustomerConnectorService getBasicHttpBindingICustomerConnectorService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICustomerConnectorService"), ICustomerConnectorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICustomerConnectorService
     */
    @WebEndpoint(name = "BasicHttpBinding_ICustomerConnectorService")
    public ICustomerConnectorService getBasicHttpBindingICustomerConnectorService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ICustomerConnectorService"), ICustomerConnectorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERCONNECTORSERVICE_EXCEPTION!= null) {
            throw CUSTOMERCONNECTORSERVICE_EXCEPTION;
        }
        return CUSTOMERCONNECTORSERVICE_WSDL_LOCATION;
    }

}
