
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.ArrayOfCachedProfileData;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.ArrayOfLookUpByForeignSystemIdRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CachedProfileData;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.ChangeUserCountryRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.ChangeUserLoyaltyStatusRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CreateUserProfileRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CustomerData;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetAssociatedAccountsReq;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetAssociatedAccountsResp;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetCustomerDataRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetExternalIdRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetExternalIdResponse;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.JurisdictionRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.JurisdictionStatusData;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.LookUpByForeignSystemIdRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.LookUpBySportsBookUserIdRequest;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.LoyaltyStatusData;
import org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.SetCurrencyRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerConnectorService", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
@XmlSeeAlso({
    com.services.bwin.xmlns.services.customerconnector._1.ObjectFactory.class,
    com.services.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.ObjectFactory.class
})
public interface ICustomerConnectorService {


    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CustomerData
     * @throws ICustomerConnectorServiceGetCustomerDataMalformedRequestFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetCustomerDataCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetCustomerDataGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetCustomerDataMasterDataRecordFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetCustomerDataUnknownSourceSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetCustomerData", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/GetCustomerData")
    @WebResult(name = "GetCustomerDataResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "GetCustomerData", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.GetCustomerData")
    @ResponseWrapper(localName = "GetCustomerDataResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.GetCustomerDataResponse")
    public CustomerData getCustomerData(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        GetCustomerDataRequest request)
        throws ICustomerConnectorServiceGetCustomerDataCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceGetCustomerDataGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceGetCustomerDataMalformedRequestFaultFaultFaultMessage, ICustomerConnectorServiceGetCustomerDataMasterDataRecordFaultFaultFaultMessage, ICustomerConnectorServiceGetCustomerDataUnknownSourceSystemFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Long
     * @throws ICustomerConnectorServiceCreateSportsUserProfileMalformedRequestFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceCreateSportsUserProfileGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceCreateSportsUserProfileExternalSystemFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CreateSportsUserProfile", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/CreateSportsUserProfile")
    @WebResult(name = "CreateSportsUserProfileResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "CreateSportsUserProfile", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.CreateSportsUserProfile")
    @ResponseWrapper(localName = "CreateSportsUserProfileResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.CreateSportsUserProfileResponse")
    public Long createSportsUserProfile(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        CreateUserProfileRequest request)
        throws ICustomerConnectorServiceCreateSportsUserProfileExternalSystemFaultFaultFaultMessage, ICustomerConnectorServiceCreateSportsUserProfileGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceCreateSportsUserProfileMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CachedProfileData
     * @throws ICustomerConnectorServiceLookUpBySportsBookUserIdCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceLookUpBySportsBookUserIdGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceLookUpBySportsBookUserIdMalformedRequestFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LookUpBySportsBookUserId", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/LookUpBySportsBookUserId")
    @WebResult(name = "LookUpBySportsBookUserIdResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "LookUpBySportsBookUserId", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.LookUpBySportsBookUserId")
    @ResponseWrapper(localName = "LookUpBySportsBookUserIdResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.LookUpBySportsBookUserIdResponse")
    public CachedProfileData lookUpBySportsBookUserId(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        LookUpBySportsBookUserIdRequest request)
        throws ICustomerConnectorServiceLookUpBySportsBookUserIdCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceLookUpBySportsBookUserIdGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceLookUpBySportsBookUserIdMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CachedProfileData
     * @throws ICustomerConnectorServiceLookUpByForeignSystemIdCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceLookUpByForeignSystemIdGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceLookUpByForeignSystemIdMalformedRequestFaultFaultFaultMessage
     */
    @WebMethod(operationName = "LookUpByForeignSystemId", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/LookUpByForeignSystemId")
    @WebResult(name = "LookUpByForeignSystemIdResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "LookUpByForeignSystemId", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.LookUpByForeignSystemId")
    @ResponseWrapper(localName = "LookUpByForeignSystemIdResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.LookUpByForeignSystemIdResponse")
    public CachedProfileData lookUpByForeignSystemId(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        LookUpByForeignSystemIdRequest request)
        throws ICustomerConnectorServiceLookUpByForeignSystemIdCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceLookUpByForeignSystemIdGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceLookUpByForeignSystemIdMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.ArrayOfCachedProfileData
     * @throws ICustomerConnectorServiceBulkLookUpByForeignSystemIdGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceBulkLookUpByForeignSystemIdCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceBulkLookUpByForeignSystemIdMalformedRequestFaultFaultFaultMessage
     */
    @WebMethod(operationName = "BulkLookUpByForeignSystemId", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/BulkLookUpByForeignSystemId")
    @WebResult(name = "BulkLookUpByForeignSystemIdResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "BulkLookUpByForeignSystemId", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.BulkLookUpByForeignSystemId")
    @ResponseWrapper(localName = "BulkLookUpByForeignSystemIdResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.BulkLookUpByForeignSystemIdResponse")
    public ArrayOfCachedProfileData bulkLookUpByForeignSystemId(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        ArrayOfLookUpByForeignSystemIdRequest request)
        throws ICustomerConnectorServiceBulkLookUpByForeignSystemIdCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceBulkLookUpByForeignSystemIdGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceBulkLookUpByForeignSystemIdMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.CachedProfileData
     * @throws ICustomerConnectorServiceChangeUserCountryGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserCountryMalformedRequestFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserCountryCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserCountryInvalidCountryFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ChangeUserCountry", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/ChangeUserCountry")
    @WebResult(name = "ChangeUserCountryResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "ChangeUserCountry", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.ChangeUserCountry")
    @ResponseWrapper(localName = "ChangeUserCountryResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.ChangeUserCountryResponse")
    public CachedProfileData changeUserCountry(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        ChangeUserCountryRequest request)
        throws ICustomerConnectorServiceChangeUserCountryCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserCountryGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserCountryInvalidCountryFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserCountryMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.LoyaltyStatusData
     * @throws ICustomerConnectorServiceChangeUserLoyaltyStatusMalformedRequestFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserLoyaltyStatusCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserLoyaltyStatusGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserLoyaltyStatusInvalidLoyaltyStatusFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ChangeUserLoyaltyStatus", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/ChangeUserLoyaltyStatus")
    @WebResult(name = "ChangeUserLoyaltyStatusResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "ChangeUserLoyaltyStatus", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.ChangeUserLoyaltyStatus")
    @ResponseWrapper(localName = "ChangeUserLoyaltyStatusResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.ChangeUserLoyaltyStatusResponse")
    public LoyaltyStatusData changeUserLoyaltyStatus(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        ChangeUserLoyaltyStatusRequest request)
        throws ICustomerConnectorServiceChangeUserLoyaltyStatusCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserLoyaltyStatusGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserLoyaltyStatusInvalidLoyaltyStatusFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserLoyaltyStatusMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetAssociatedAccountsResp
     * @throws ICustomerConnectorServiceGetAssociatedAccountsGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetAssociatedAccountsCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetAssociatedAccountsMalformedRequestFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAssociatedAccounts", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/GetAssociatedAccounts")
    @WebResult(name = "GetAssociatedAccountsResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "GetAssociatedAccounts", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.GetAssociatedAccounts")
    @ResponseWrapper(localName = "GetAssociatedAccountsResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.GetAssociatedAccountsResponse")
    public GetAssociatedAccountsResp getAssociatedAccounts(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        GetAssociatedAccountsReq request)
        throws ICustomerConnectorServiceGetAssociatedAccountsCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceGetAssociatedAccountsGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceGetAssociatedAccountsMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @throws ICustomerConnectorServiceSetCurrencyCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceSetCurrencyGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceSetCurrencyMalformedRequestFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetCurrency", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/SetCurrency")
    @RequestWrapper(localName = "SetCurrency", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.SetCurrency")
    @ResponseWrapper(localName = "SetCurrencyResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.SetCurrencyResponse")
    public void setCurrency(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        SetCurrencyRequest request)
        throws ICustomerConnectorServiceSetCurrencyCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceSetCurrencyGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceSetCurrencyMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.JurisdictionStatusData
     * @throws ICustomerConnectorServiceChangeUserJurisdictionGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserJurisdictionCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserJurisdictionMalformedRequestFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceChangeUserJurisdictionJurisdictionInvalidFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ChangeUserJurisdiction", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/ChangeUserJurisdiction")
    @WebResult(name = "ChangeUserJurisdictionResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "ChangeUserJurisdiction", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.ChangeUserJurisdiction")
    @ResponseWrapper(localName = "ChangeUserJurisdictionResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.ChangeUserJurisdictionResponse")
    public JurisdictionStatusData changeUserJurisdiction(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        JurisdictionRequest request)
        throws ICustomerConnectorServiceChangeUserJurisdictionCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserJurisdictionGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserJurisdictionJurisdictionInvalidFaultFaultFaultMessage, ICustomerConnectorServiceChangeUserJurisdictionMalformedRequestFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.bwin_sportsbook_customerconnector_service_datacontracts.GetExternalIdResponse
     * @throws ICustomerConnectorServiceGetExternalIdCustomerNotFoundFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetExternalIdGeneralTechnicalFaultFaultFaultMessage
     * @throws ICustomerConnectorServiceGetExternalIdMalformedRequestFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetExternalId", action = "http://xmlns.bwin.com/services/CustomerConnector/1.2/ICustomerConnectorService/GetExternalId")
    @WebResult(name = "GetExternalIdResult", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
    @RequestWrapper(localName = "GetExternalId", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.GetExternalId")
    @ResponseWrapper(localName = "GetExternalIdResponse", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2", className = "com.services.bwin.xmlns.services.customerconnector._1.GetExternalIdResponse")
    public GetExternalIdResponse getExternalId(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/CustomerConnector/1.2")
        GetExternalIdRequest request)
        throws ICustomerConnectorServiceGetExternalIdCustomerNotFoundFaultFaultFaultMessage, ICustomerConnectorServiceGetExternalIdGeneralTechnicalFaultFaultFaultMessage, ICustomerConnectorServiceGetExternalIdMalformedRequestFaultFaultFaultMessage
    ;

}
