
package com.services.bwin.xmlns.services.earlypayoutservice._3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EarlyPayoutService", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", wsdlLocation = "http://integration.earlypayout.bwin.dev/3.0/EarlyPayoutService.svc?wsdl")
public class EarlyPayoutService
    extends Service
{

    private final static URL EARLYPAYOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EARLYPAYOUTSERVICE_EXCEPTION;
    private final static QName EARLYPAYOUTSERVICE_QNAME = new QName("http://xmlns.bwin.com/services/EarlyPayoutService/3.0", "EarlyPayoutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://integration.earlypayout.bwin.dev/3.0/EarlyPayoutService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EARLYPAYOUTSERVICE_WSDL_LOCATION = url;
        EARLYPAYOUTSERVICE_EXCEPTION = e;
    }

    public EarlyPayoutService() {
        super(__getWsdlLocation(), EARLYPAYOUTSERVICE_QNAME);
    }

    public EarlyPayoutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EARLYPAYOUTSERVICE_QNAME, features);
    }

    public EarlyPayoutService(URL wsdlLocation) {
        super(wsdlLocation, EARLYPAYOUTSERVICE_QNAME);
    }

    public EarlyPayoutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EARLYPAYOUTSERVICE_QNAME, features);
    }

    public EarlyPayoutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EarlyPayoutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IEarlyPayoutService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEarlyPayoutService")
    public IEarlyPayoutService getBasicHttpBindingIEarlyPayoutService() {
        return super.getPort(new QName("http://xmlns.bwin.com/services/EarlyPayoutService/3.0", "BasicHttpBinding_IEarlyPayoutService"), IEarlyPayoutService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEarlyPayoutService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEarlyPayoutService")
    public IEarlyPayoutService getBasicHttpBindingIEarlyPayoutService(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.bwin.com/services/EarlyPayoutService/3.0", "BasicHttpBinding_IEarlyPayoutService"), IEarlyPayoutService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EARLYPAYOUTSERVICE_EXCEPTION!= null) {
            throw EARLYPAYOUTSERVICE_EXCEPTION;
        }
        return EARLYPAYOUTSERVICE_WSDL_LOCATION;
    }

}
