
package com.services.bwin.xmlns.services.earlypayoutservice._3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.services.bwin.xmlns.types.earlypayoutservice._3.AutoCashoutResponse;
import com.services.bwin.xmlns.types.earlypayoutservice._3.CheckPossibleEarlyPayoutRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.CheckPossibleEarlyPayoutResponse;
import com.services.bwin.xmlns.types.earlypayoutservice._3.EarlyPayoutRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.EarlyPayoutResponse;
import com.services.bwin.xmlns.types.earlypayoutservice._3.GetAutoCashoutRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.GetAutoCashoutResponse;
import com.services.bwin.xmlns.types.earlypayoutservice._3.GetEarlyPayoutConstraintsRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.GetEarlyPayoutConstraintsResponse;
import com.services.bwin.xmlns.types.earlypayoutservice._3.GetStatusRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.GetStatusResponse;
import com.services.bwin.xmlns.types.earlypayoutservice._3.RemoveAutoCashoutRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.SetAutoCashoutRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.UndoEarlyPayoutRequest;
import com.services.bwin.xmlns.types.earlypayoutservice._3.UndoEarlyPayoutResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEarlyPayoutService", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
@XmlSeeAlso({
    com.services.serialization.arrays.ObjectFactory.class,
    com.services.bwin.xmlns.services.earlypayoutservice._3.ObjectFactory.class,
    com.services.bwin.xmlns.types.earlypayoutservice._3.ObjectFactory.class,
    com.services.serialization.ObjectFactory.class
})
public interface IEarlyPayoutService {


    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.EarlyPayoutResponse
     * @throws IEarlyPayoutServiceEarlyPayoutTechnicalFaultFaultFaultMessage
     * @throws IEarlyPayoutServiceEarlyPayoutRequestIdBlockedFaultFaultFaultMessage
     */
    @WebMethod(operationName = "EarlyPayout", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/EarlyPayout")
    @WebResult(name = "EarlyPayoutResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "EarlyPayout", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.EarlyPayout")
    @ResponseWrapper(localName = "EarlyPayoutResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.EarlyPayoutResponse")
    public EarlyPayoutResponse earlyPayout(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        EarlyPayoutRequest request)
        throws IEarlyPayoutServiceEarlyPayoutRequestIdBlockedFaultFaultFaultMessage, IEarlyPayoutServiceEarlyPayoutTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.GetStatusResponse
     * @throws IEarlyPayoutServiceGetStatusTechnicalFaultFaultFaultMessage
     * @throws IEarlyPayoutServiceGetStatusRequestIdNotFoundFaultFaultFaultMessage
     * @throws IEarlyPayoutServiceGetStatusRequestIdBlockedFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetStatus", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/GetStatus")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.GetStatusResponse")
    public GetStatusResponse getStatus(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        GetStatusRequest request)
        throws IEarlyPayoutServiceGetStatusRequestIdBlockedFaultFaultFaultMessage, IEarlyPayoutServiceGetStatusRequestIdNotFoundFaultFaultFaultMessage, IEarlyPayoutServiceGetStatusTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.GetEarlyPayoutConstraintsResponse
     * @throws IEarlyPayoutServiceGetEarlyPayoutConstraintsTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetEarlyPayoutConstraints", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/GetEarlyPayoutConstraints")
    @WebResult(name = "GetEarlyPayoutConstraintsResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "GetEarlyPayoutConstraints", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.GetEarlyPayoutConstraints")
    @ResponseWrapper(localName = "GetEarlyPayoutConstraintsResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.GetEarlyPayoutConstraintsResponse")
    public GetEarlyPayoutConstraintsResponse getEarlyPayoutConstraints(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        GetEarlyPayoutConstraintsRequest request)
        throws IEarlyPayoutServiceGetEarlyPayoutConstraintsTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.CheckPossibleEarlyPayoutResponse
     * @throws IEarlyPayoutServiceCheckPossibleEarlyPayoutTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CheckPossibleEarlyPayout", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/CheckPossibleEarlyPayout")
    @WebResult(name = "CheckPossibleEarlyPayoutResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "CheckPossibleEarlyPayout", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.CheckPossibleEarlyPayout")
    @ResponseWrapper(localName = "CheckPossibleEarlyPayoutResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.CheckPossibleEarlyPayoutResponse")
    public CheckPossibleEarlyPayoutResponse checkPossibleEarlyPayout(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        CheckPossibleEarlyPayoutRequest request)
        throws IEarlyPayoutServiceCheckPossibleEarlyPayoutTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.CheckPossibleEarlyPayoutResponse
     * @throws IEarlyPayoutServiceCheckPossibleEarlyPayoutAndSubscribeTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "CheckPossibleEarlyPayoutAndSubscribe", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/CheckPossibleEarlyPayoutAndSubscribe")
    @WebResult(name = "CheckPossibleEarlyPayoutAndSubscribeResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "CheckPossibleEarlyPayoutAndSubscribe", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.CheckPossibleEarlyPayoutAndSubscribe")
    @ResponseWrapper(localName = "CheckPossibleEarlyPayoutAndSubscribeResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.CheckPossibleEarlyPayoutAndSubscribeResponse")
    public CheckPossibleEarlyPayoutResponse checkPossibleEarlyPayoutAndSubscribe(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        CheckPossibleEarlyPayoutRequest request)
        throws IEarlyPayoutServiceCheckPossibleEarlyPayoutAndSubscribeTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.UndoEarlyPayoutResponse
     * @throws IEarlyPayoutServiceUndoEarlyPayoutTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "UndoEarlyPayout", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/UndoEarlyPayout")
    @WebResult(name = "UndoEarlyPayoutResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "UndoEarlyPayout", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.UndoEarlyPayout")
    @ResponseWrapper(localName = "UndoEarlyPayoutResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.UndoEarlyPayoutResponse")
    public UndoEarlyPayoutResponse undoEarlyPayout(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        UndoEarlyPayoutRequest request)
        throws IEarlyPayoutServiceUndoEarlyPayoutTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.AutoCashoutResponse
     * @throws IEarlyPayoutServiceSetAutoCashoutTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "SetAutoCashout", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/SetAutoCashout")
    @WebResult(name = "SetAutoCashoutResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "SetAutoCashout", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.SetAutoCashout")
    @ResponseWrapper(localName = "SetAutoCashoutResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.SetAutoCashoutResponse")
    public AutoCashoutResponse setAutoCashout(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        SetAutoCashoutRequest request)
        throws IEarlyPayoutServiceSetAutoCashoutTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.AutoCashoutResponse
     * @throws IEarlyPayoutServiceRemoveAutoCashoutTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "RemoveAutoCashout", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/RemoveAutoCashout")
    @WebResult(name = "RemoveAutoCashoutResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "RemoveAutoCashout", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.RemoveAutoCashout")
    @ResponseWrapper(localName = "RemoveAutoCashoutResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.RemoveAutoCashoutResponse")
    public AutoCashoutResponse removeAutoCashout(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        RemoveAutoCashoutRequest request)
        throws IEarlyPayoutServiceRemoveAutoCashoutTechnicalFaultFaultFaultMessage
    ;

    /**
     * 
     * @param request
     * @return
     *     returns com.services.bwin.xmlns.types.earlypayoutservice._3.GetAutoCashoutResponse
     * @throws IEarlyPayoutServiceGetAutoCashoutTechnicalFaultFaultFaultMessage
     */
    @WebMethod(operationName = "GetAutoCashout", action = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0/IEarlyPayoutService/GetAutoCashout")
    @WebResult(name = "GetAutoCashoutResult", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
    @RequestWrapper(localName = "GetAutoCashout", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.GetAutoCashout")
    @ResponseWrapper(localName = "GetAutoCashoutResponse", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0", className = "com.services.bwin.xmlns.services.earlypayoutservice._3.GetAutoCashoutResponse")
    public GetAutoCashoutResponse getAutoCashout(
        @WebParam(name = "request", targetNamespace = "http://xmlns.bwin.com/services/EarlyPayoutService/3.0")
        GetAutoCashoutRequest request)
        throws IEarlyPayoutServiceGetAutoCashoutTechnicalFaultFaultFaultMessage
    ;

}
