
package com.services.bwin.xmlns.services.earlypayoutservice._3;

import javax.xml.ws.WebFault;
import com.services.bwin.xmlns.types.earlypayoutservice._3.RequestIdNotFoundFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RequestIdNotFoundFault", targetNamespace = "http://xmlns.bwin.com/types/EarlyPayoutService/3.0")
public class IEarlyPayoutServiceGetStatusRequestIdNotFoundFaultFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RequestIdNotFoundFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IEarlyPayoutServiceGetStatusRequestIdNotFoundFaultFaultFaultMessage(String message, RequestIdNotFoundFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IEarlyPayoutServiceGetStatusRequestIdNotFoundFaultFaultFaultMessage(String message, RequestIdNotFoundFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.services.bwin.xmlns.types.earlypayoutservice._3.RequestIdNotFoundFault
     */
    public RequestIdNotFoundFault getFaultInfo() {
        return faultInfo;
    }

}
